### PR TITLE
Use glium's new macro instead of implementing Vertex ourselves

### PR DESCRIPTION
**Pull request by tomaka**

### CODE REVIEW

**Comment by aepsil0n** [comment]
Ah, that's nice.

**Comment by tomaka** [comment]
(note: wait until travis passes, I'm doing this change blindly)

**Comment by aepsil0n** [comment]
Oh, I don't have write access to this repo anyway. But I could test the example locally.

**Comment by tomaka** [comment]
@aepsil0n Slightly off-topic, but if you have similar code in your projects I encourage you to change it, as I'm going to make some changes in the `Vertex` trait.

**Comment by aepsil0n** [comment]
I just removed the now superfluous imports, see [here](https://github.com/tomaka/glium_graphics/pull/1).

**Pull request merged**
