### PR TITLE
Make glium_graphics window backend agnostic.

### LINKED ISSUE #29: Make glium_graphics window backend agnostic.
* [x] Add `OpenGLWindow` trait with these methods(`get_proc_address`, `is_current`, `make_current`) to `window` crate -- issue PistonDevelopers/window#44, PR PistonDevelopers/window#45
* [ ] Impl glium `Backend` trait for `T: OpenGLWindow` and add fn to create context -- PR #30
* [x] Impl `OpenGLWindow` in window backends:
      * [x] glutin_window -- PR PistonDevelopers/glutin_window#19
      * [x] glfw_window -- PR PistonDevelopers/glfw_window#97
      * [x] sdl2_window -- PR PistonDevelopers/sdl2_window#151

### PR DESCRIPTION
**Pull request by Potpourri**
close #29

### CODE REVIEW

**Comment by bvssvni** [comment]
Can you add some docs of when to use `GliumWindow` and `PistonWindow`?

**Comment by tomaka** [comment]
Note that `impl Backend` will ultimately need to be made unsafe because of https://github.com/tomaka/glium/pull/700

**Comment by Potpourri** [comment]
Yes, I add docs and made impl Backend unsafe later, now it yet not ready. Work In Progress.

**Comment by Potpourri** [comment]
@bvssvni I finished it.

**Comment by bvssvni** [comment]
Nice! :tada:

**Pull request merged**
